---
- name: ESXi Info 
  hosts: localhost
  vars:
    vcenter_server: "172.20.1.220"
    vcenter_username: "administrator@vsphere.local"
    vcenter_password: "Cbi@202104*"
    esxi_hostname: "hx-node1.lab.local"
  tasks:
    - name: Gather product version info for ESXi from vCenter
      community.vmware.vmware_host_facts:
          hostname: "{{ vcenter_server }}"
          username: "{{ vcenter_username }}"
          password: "{{ vcenter_password }}"
          esxi_hostname: "{{ esxi_hostname }}"
          validate_certs: no
          schema: vsphere
          properties:
            - config.product
            - config.option
            - runtime.connectionState
            - runtime.powerState
            - hardware.memorySize
            - hardware.cpuInfo.numCpuCores
            - config.product.apiVersion
            - overallStatus
  
     
  
    
